/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:887bd8fd-701c-48e2-bcb1-fce98efea7cd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JjRfW8k0k",
    "aws_user_pools_web_client_id": "7i06cmnqb4mvktqlmfaatenvna",
    "oauth": {}
};


export default awsmobile;
